/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import control.*;
import java.sql.SQLException;
import model.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import tabel.*;

public class AdminMainView extends javax.swing.JFrame {

    String action = null;
    int selectedId = 0;
    List<Pegawai> listPegawai;
    List<Konsumen> listKonsumen;
    
    private PegawaiControl PC;
    private KonsumenControl KC;
    
    int globalIndexPegawai = -1;
    int globalIndexKonsumen = -1;
    
    public AdminMainView() {
        initComponents();
        PC = new PegawaiControl();
        KC = new KonsumenControl();
        
        clearText();
        showTablePegawaiForAdmin();
        showTableKonsumenForAdmin();
    }
    
    public void clearText(){
        InputSearchCustomer.setText("");
        InputSearchPegawai.setText("");
    }
    
    public void showTablePegawaiForAdmin(){
        tablePegawai.setModel(PC.showTableForAdmin(""));
    }
    
    public void showTableKonsumenForAdmin(){
        tableKonsumen.setModel(KC.showTableForAdmin(""));
    }
    
    public void recallTabel(){
        tablePegawai.setModel(PC.showTableForAdmin(""));
        tableKonsumen.setModel(KC.showTableForAdmin(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePegawai = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKonsumen = new javax.swing.JTable();
        InputSearchCustomer = new javax.swing.JTextField();
        InputSearchPegawai = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SearchCustomerBtn = new javax.swing.JButton();
        SearchPegawaiBtn = new javax.swing.JButton();
        CjakraLogo = new javax.swing.JLabel();
        MoreInfoLogo = new javax.swing.JLabel();
        CreateLabel = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HapusLabel = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UpdateLabel = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DetailLabel = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PengaturanPanel = new javax.swing.JLayeredPane();
        SettingsIcon = new javax.swing.JLabel();
        SettingsLabel = new javax.swing.JLabel();
        KeluarPanel = new javax.swing.JLayeredPane();
        KeluarLabel = new javax.swing.JLabel();
        KeluarIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BackgroundPanel.setBackground(new java.awt.Color(0, 0, 0));
        BackgroundPanel.setForeground(new java.awt.Color(0, 0, 0));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(49, 49, 49));
        kGradientPanel1.setkGradientFocus(100);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 0));

        tablePegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePegawai);

        tableKonsumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKonsumen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKonsumenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableKonsumen);

        InputSearchCustomer.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        InputSearchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputSearchCustomerActionPerformed(evt);
            }
        });

        InputSearchPegawai.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Data Customer");

        jLabel14.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Data Pegawai");

        SearchCustomerBtn.setBackground(new java.awt.Color(0, 0, 0));
        SearchCustomerBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        SearchCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        SearchCustomerBtn.setText("Cari");
        SearchCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCustomerBtnActionPerformed(evt);
            }
        });

        SearchPegawaiBtn.setBackground(new java.awt.Color(0, 0, 0));
        SearchPegawaiBtn.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        SearchPegawaiBtn.setForeground(new java.awt.Color(255, 255, 255));
        SearchPegawaiBtn.setText("Cari");
        SearchPegawaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPegawaiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InputSearchPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchPegawaiBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InputSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchCustomerBtn)))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputSearchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchCustomerBtn)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputSearchPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchPegawaiBtn)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        BackgroundPanel.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 12, -1, -1));

        CjakraLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Cjakra 40x15@3x.png"))); // NOI18N
        BackgroundPanel.add(CjakraLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        MoreInfoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/Info.png"))); // NOI18N
        MoreInfoLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MoreInfoLogoMouseClicked(evt);
            }
        });
        BackgroundPanel.add(MoreInfoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 25, -1, -1));

        CreateLabel.setkEndColor(new java.awt.Color(49, 49, 49));
        CreateLabel.setkStartColor(new java.awt.Color(49, 49, 49));
        CreateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateLabelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buat");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/createicon.png"))); // NOI18N

        javax.swing.GroupLayout CreateLabelLayout = new javax.swing.GroupLayout(CreateLabel);
        CreateLabel.setLayout(CreateLabelLayout);
        CreateLabelLayout.setHorizontalGroup(
            CreateLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        CreateLabelLayout.setVerticalGroup(
            CreateLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel1)
                .addComponent(jLabel2))
        );

        BackgroundPanel.add(CreateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 104, 330, -1));

        HapusLabel.setkEndColor(new java.awt.Color(49, 49, 49));
        HapusLabel.setkStartColor(new java.awt.Color(49, 49, 49));
        HapusLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HapusLabelMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hapus");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/deleteicon.png"))); // NOI18N

        javax.swing.GroupLayout HapusLabelLayout = new javax.swing.GroupLayout(HapusLabel);
        HapusLabel.setLayout(HapusLabelLayout);
        HapusLabelLayout.setHorizontalGroup(
            HapusLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HapusLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );
        HapusLabelLayout.setVerticalGroup(
            HapusLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HapusLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel3)
                .addComponent(jLabel4))
        );

        BackgroundPanel.add(HapusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 172, 330, -1));

        UpdateLabel.setkEndColor(new java.awt.Color(49, 49, 49));
        UpdateLabel.setkStartColor(new java.awt.Color(49, 49, 49));
        UpdateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateLabelMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/updateicon.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ubah");

        javax.swing.GroupLayout UpdateLabelLayout = new javax.swing.GroupLayout(UpdateLabel);
        UpdateLabel.setLayout(UpdateLabelLayout);
        UpdateLabelLayout.setHorizontalGroup(
            UpdateLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );
        UpdateLabelLayout.setVerticalGroup(
            UpdateLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel5)
                .addComponent(jLabel6))
        );

        BackgroundPanel.add(UpdateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 240, 330, -1));

        DetailLabel.setkEndColor(new java.awt.Color(49, 49, 49));
        DetailLabel.setkStartColor(new java.awt.Color(49, 49, 49));
        DetailLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetailLabelMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/detailicon.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Poppins", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Detail");

        javax.swing.GroupLayout DetailLabelLayout = new javax.swing.GroupLayout(DetailLabel);
        DetailLabel.setLayout(DetailLabelLayout);
        DetailLabelLayout.setHorizontalGroup(
            DetailLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );
        DetailLabelLayout.setVerticalGroup(
            DetailLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(jLabel8)
                .addComponent(jLabel7))
        );

        BackgroundPanel.add(DetailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 308, 330, -1));

        PengaturanPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PengaturanPanelMouseClicked(evt);
            }
        });

        SettingsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/settingsicon.png"))); // NOI18N

        SettingsLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        SettingsLabel.setForeground(new java.awt.Color(255, 255, 255));
        SettingsLabel.setText("Pengaturan");

        PengaturanPanel.setLayer(SettingsIcon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PengaturanPanel.setLayer(SettingsLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PengaturanPanelLayout = new javax.swing.GroupLayout(PengaturanPanel);
        PengaturanPanel.setLayout(PengaturanPanelLayout);
        PengaturanPanelLayout.setHorizontalGroup(
            PengaturanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengaturanPanelLayout.createSequentialGroup()
                .addComponent(SettingsIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettingsLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PengaturanPanelLayout.setVerticalGroup(
            PengaturanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SettingsIcon)
            .addComponent(SettingsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        BackgroundPanel.add(PengaturanPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 534, 326, -1));

        KeluarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeluarPanelMouseClicked(evt);
            }
        });

        KeluarLabel.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        KeluarLabel.setForeground(new java.awt.Color(255, 255, 255));
        KeluarLabel.setText("Keluar");

        KeluarIcon.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        KeluarIcon.setForeground(new java.awt.Color(255, 255, 255));
        KeluarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/logouticon.png"))); // NOI18N
        KeluarIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KeluarIconMouseClicked(evt);
            }
        });

        KeluarPanel.setLayer(KeluarLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        KeluarPanel.setLayer(KeluarIcon, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout KeluarPanelLayout = new javax.swing.GroupLayout(KeluarPanel);
        KeluarPanel.setLayout(KeluarPanelLayout);
        KeluarPanelLayout.setHorizontalGroup(
            KeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeluarPanelLayout.createSequentialGroup()
                .addComponent(KeluarIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KeluarLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        KeluarPanelLayout.setVerticalGroup(
            KeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KeluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(KeluarIcon)
                .addComponent(KeluarLabel, javax.swing.GroupLayout.Alignment.LEADING))
        );

        BackgroundPanel.add(KeluarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 560, 326, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InputSearchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputSearchCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputSearchCustomerActionPerformed

    private void KeluarIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarIconMouseClicked
        LoginView MV = new LoginView();
        this.dispose();
        MV.setVisible(true);
    }//GEN-LAST:event_KeluarIconMouseClicked

    private void MoreInfoLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoreInfoLogoMouseClicked
        AboutUsView MV = new AboutUsView();
        MV.setVisible(true); 
    }//GEN-LAST:event_MoreInfoLogoMouseClicked

    private void SearchPegawaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPegawaiBtnActionPerformed
        try {
            TabelTampilPegawai TTP = PC.showTableForAdmin(InputSearchPegawai.getText());
            
            if (tablePegawai.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan","Konfirmasi", JOptionPane.DEFAULT_OPTION);
            } else {
                tablePegawai.setModel(TTP);
            }
        } catch (Exception e) {
            System.out.println("Error :" + e.getMessage());
        }
    }//GEN-LAST:event_SearchPegawaiBtnActionPerformed

    private void SearchCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCustomerBtnActionPerformed
//        Pegawai tempP = null;
//        Konsumen tempK = null;
//        
//        if(globalIndexPegawai != -1){
//
//        }else if(globalIndexKonsumen != -1){            
//            tempP = PC.searchOnlyId(Integer.toString(globalIndexKonsumen));
//
//        }else{
//            ErrorView ev = new ErrorView();
//            ev.setVisible(true);
//        }
//        
//        clearText();
        try {
            TabelKonsumen TK = KC.showTableForAdmin(InputSearchCustomer.getText());
            
            if (tablePegawai.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan","Konfirmasi", JOptionPane.DEFAULT_OPTION);
            } else {
                tableKonsumen.setModel(TK);
            }
        } catch (Exception e) {
            System.out.println("Error :" + e.getMessage());
        }
    }//GEN-LAST:event_SearchCustomerBtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void HapusLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusLabelMouseClicked
        Pegawai tempP = null;
        Konsumen tempK = null;
        
        if(globalIndexKonsumen != -1){
            KC.deleteDataKonsumenById(globalIndexKonsumen);
        }else if(globalIndexPegawai != -1){            
            PC.deleteDataPegawaiById(globalIndexPegawai);
        }else{
            ErrorView ev = new ErrorView();
            ev.setVisible(true);
        }
        
        clearText();
        recallTabel();
    }//GEN-LAST:event_HapusLabelMouseClicked

    private void UpdateLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateLabelMouseClicked
        Pegawai tempP = null;
        Konsumen tempK = null;
        
        if(globalIndexKonsumen != -1){

        }else if(globalIndexPegawai != -1){            
            tempP = PC.searchOnlyId(Integer.toString(globalIndexPegawai));
            
            AdminUpdateView MVV = new AdminUpdateView(tempP);
            this.dispose();
            MVV.setVisible(true);
        }else{
            System.out.println("Nope");
        }
        
        clearText();
    }//GEN-LAST:event_UpdateLabelMouseClicked

    private void DetailLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailLabelMouseClicked
//        AdminDetailView adv = new AdminDetailView();
//        this.dispose();
//        adv.setVisible(true);
        OnDevView odv = new OnDevView();
        odv.setVisible(true);
    }//GEN-LAST:event_DetailLabelMouseClicked

    private void PengaturanPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PengaturanPanelMouseClicked
        SettingsView sv = new SettingsView();
        this.dispose();
        sv.setVisible(true);
    }//GEN-LAST:event_PengaturanPanelMouseClicked

    private void KeluarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarPanelMouseClicked
        LoginView lv = new LoginView();
        this.dispose();
        lv.setVisible(true);
    }//GEN-LAST:event_KeluarPanelMouseClicked

    private void CreateLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateLabelMouseClicked
        AdminCreateView acv = new AdminCreateView();
        this.dispose();
        acv.setVisible(true);
    }//GEN-LAST:event_CreateLabelMouseClicked

    private void tableKonsumenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKonsumenMouseClicked
        int indexKonsumen = -1;
        int indexPegawai = -1;

        globalIndexKonsumen = -1;
        globalIndexPegawai = -1;
        
        int clickedRow = tableKonsumen.getSelectedRow();
        TableModel tableModel = tableKonsumen.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        globalIndexKonsumen = selectedId;
    }//GEN-LAST:event_tableKonsumenMouseClicked

    private void tablePegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePegawaiMouseClicked
        int indexKonsumen = -1;
        int indexPegawai = -1;
        
        globalIndexKonsumen = -1;
        globalIndexPegawai = -1;
        
        int clickedRow = tablePegawai.getSelectedRow();
        TableModel tableModel = tablePegawai.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        globalIndexPegawai = selectedId;
    }//GEN-LAST:event_tablePegawaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel CjakraLogo;
    private keeptoo.KGradientPanel CreateLabel;
    private keeptoo.KGradientPanel DetailLabel;
    private keeptoo.KGradientPanel HapusLabel;
    private javax.swing.JTextField InputSearchCustomer;
    private javax.swing.JTextField InputSearchPegawai;
    private javax.swing.JLabel KeluarIcon;
    private javax.swing.JLabel KeluarLabel;
    private javax.swing.JLayeredPane KeluarPanel;
    private javax.swing.JLabel MoreInfoLogo;
    private javax.swing.JLayeredPane PengaturanPanel;
    private javax.swing.JButton SearchCustomerBtn;
    private javax.swing.JButton SearchPegawaiBtn;
    private javax.swing.JLabel SettingsIcon;
    private javax.swing.JLabel SettingsLabel;
    private keeptoo.KGradientPanel UpdateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable tableKonsumen;
    private javax.swing.JTable tablePegawai;
    // End of variables declaration//GEN-END:variables
}
